server:
  port: 8881

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jooq
    username: root
    password: Aiccdev1!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true