server:
  port: 8881

spring:
  datasource:
#    url: jdbc:tc:mariadb:10.9.2://test
    url: [jdbc URL]
    username: [DB username]
    password: [DB papssword]
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true